/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jllvm.llvm;

public class Analysis {
  public static SWIGTYPE_p_LLVMBool LLVMVerifyModule(SWIGTYPE_p_LLVMOpaqueModule M, LLVMVerifierFailureAction Action, SWIGTYPE_p_p_char OutMessage) {
    return new SWIGTYPE_p_LLVMBool(AnalysisJNI.LLVMVerifyModule(SWIGTYPE_p_LLVMOpaqueModule.getCPtr(M), Action.swigValue(), SWIGTYPE_p_p_char.getCPtr(OutMessage)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMVerifyFunction(SWIGTYPE_p_LLVMOpaqueValue Fn, LLVMVerifierFailureAction Action) {
    return new SWIGTYPE_p_LLVMBool(AnalysisJNI.LLVMVerifyFunction(SWIGTYPE_p_LLVMOpaqueValue.getCPtr(Fn), Action.swigValue()), true);
  }

  public static void LLVMViewFunctionCFG(SWIGTYPE_p_LLVMOpaqueValue Fn) {
    AnalysisJNI.LLVMViewFunctionCFG(SWIGTYPE_p_LLVMOpaqueValue.getCPtr(Fn));
  }

  public static void LLVMViewFunctionCFGOnly(SWIGTYPE_p_LLVMOpaqueValue Fn) {
    AnalysisJNI.LLVMViewFunctionCFGOnly(SWIGTYPE_p_LLVMOpaqueValue.getCPtr(Fn));
  }

}
