/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jllvm.llvm;

class BitReaderJNI {
  public final static native long LLVMParseBitcode(long jarg1, long jarg2, long jarg3);
  public final static native long LLVMParseBitcodeInContext(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long LLVMGetBitcodeModuleInContext(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long LLVMGetBitcodeModule(long jarg1, long jarg2, long jarg3);
  public final static native long LLVMGetBitcodeModuleProviderInContext(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long LLVMGetBitcodeModuleProvider(long jarg1, long jarg2, long jarg3);
}
